
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 68;
  public static final int SEQ = 8;
  public static final int FORALL = 25;
  public static final int CHAR_LIT = 65;
  public static final int GTEQ = 47;
  public static final int MULT = 50;
  public static final int CHAR = 6;
  public static final int LTEQ = 46;
  public static final int CONCAT = 41;
  public static final int SEMI = 59;
  public static final int LPAREN = 53;
  public static final int EXPO = 52;
  public static final int INT = 2;
  public static final int RAT_LIT = 66;
  public static final int MINUS = 49;
  public static final int RPAREN = 54;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int LT = 44;
  public static final int OR = 35;
  public static final int IN = 26;
  public static final int TDEF = 13;
  public static final int COMMA = 61;
  public static final int BOOL = 3;
  public static final int FI = 18;
  public static final int DIV = 51;
  public static final int THREAD = 10;
  public static final int RAT = 4;
  public static final int PLUS = 48;
  public static final int ASSIGN = 31;
  public static final int MAIN = 30;
  public static final int IF = 17;
  public static final int DOT = 62;
  public static final int EOF = 0;
  public static final int OD = 23;
  public static final int RETURN = 15;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int PIPE = 39;
  public static final int INTERSECTION = 38;
  public static final int BREAK = 27;
  public static final int FDEF = 14;
  public static final int EQ = 43;
  public static final int LBRACK = 57;
  public static final int TOP = 11;
  public static final int ARROW = 32;
  public static final int COLON = 60;
  public static final int LBRACE = 55;
  public static final int DICT = 7;
  public static final int ELSE = 20;
  public static final int FUNC = 12;
  public static final int RBRACK = 58;
  public static final int READ = 28;
  public static final int DIFFERENCE = 40;
  public static final int WHILE = 21;
  public static final int FLOAT = 5;
  public static final int RBRACE = 56;
  public static final int THEN = 19;
  public static final int ALIAS = 16;
  public static final int FALSE = 37;
  public static final int STRING_LIT = 67;
  public static final int INT_LIT = 64;
  public static final int GT = 45;
  public static final int ELIF = 24;
  public static final int PRINT = 29;
  public static final int DO = 22;
  public static final int NOTEQ = 42;
  public static final int SET = 9;
  public static final int IDENTIFIER = 63;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOL",
  "RAT",
  "FLOAT",
  "CHAR",
  "DICT",
  "SEQ",
  "SET",
  "THREAD",
  "TOP",
  "FUNC",
  "TDEF",
  "FDEF",
  "RETURN",
  "ALIAS",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "OD",
  "ELIF",
  "FORALL",
  "IN",
  "BREAK",
  "READ",
  "PRINT",
  "MAIN",
  "ASSIGN",
  "ARROW",
  "NOT",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "INTERSECTION",
  "PIPE",
  "DIFFERENCE",
  "CONCAT",
  "NOTEQ",
  "EQ",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "EXPO",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "SEMI",
  "COLON",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "INT_LIT",
  "CHAR_LIT",
  "RAT_LIT",
  "STRING_LIT",
  "FLOAT_LIT"
  };
}

